public class PrimitiveDataType {
    public void print1(){
        //we will create some datatype variables and print it.
        string batchName = 'Batch 15';
        integer totalCandidates = 54; //will this work?
        boolean isAdminCompleted = true;

        string batchDescription = batchName + ' has ' + totalCandidates + ' candidates, and is the best';
        system.debug(batchDescription);
    

     

        
    }
    
}