public  class SalesforceDevoleper {
    public void myFirstCode() {
        system.debug('faveri sehir NY');
        system.debug('favori filim Opasny Meted');
        system.debug('favori mevsim Yaz');

    }

    public void myCar(){
        String marka = 'Mercedes';
        String model = 'AMG SL';
        String renk= ' Beyaz';
        String benimArabam = 'Bayaz Renkli Mercedes';
        System.debug(marka);
        System.debug(model);
        System.debug(renk);
        System.debug(benimArabam);
        

    }
}