public class MapDemo {
    public static void mapStringInteger() {

        Map<String,Integer> map1=new Map<String,Integer>();
        map1.put('one',101);
        map1.put('two',202);
        map1.put('tree',303);
        map1.put('one',1001);
        System.debug(map1);


        List<Integer> l = map1.values();

        Map <String,String> map2;
        Map <String,Integer>map3;
        Map<Integer,String> map4;
        Map<Integer,Decimal> map5;
        map5.values();
        Map<Boolean,Decimal> map6;
        Map<Date,String> map7;
        Map<String,List<String>> map8;

        

    }
}