SoqlDemo.accountSOQL1();
SoqlDemo.accountSOQLOneR();
SoqlDemo.accountSOQL3();
SoqlDemo.projectSoqlFilter();
SoqlDemo.projectSoqlFilter('new ');
system.debug('---');
SoqlDemo.projectSoqlFilter('In-progress');

soqlDemo2.accountContactSOQL();

soqlDemo2.childToParent2();


//SoqlOrnekler.selectIndustry();
SoqlOrnekler.selectIndustry('Education');
SoqlOrnekler.selectIndustry('Energy');

SoqlOrnekler.childToParent();




